### ISSUE TITLE
Multiple humans crash Morse when explicitly naming them

### ISSUE THREAD

**Issue by pronobis** [morse-simulator/morse#558]
When multiple humans are added to the simulation like this:

```
    # Human1
    human1 = Human(name="human1")
    human1.translate(2, -8, 0)

    # Human2 
    human2 = Human(name="human2")
    human2.translate(2, -6, 0)

    # Setup the environment
    environment_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), '../data/map.blend')
    environment = Environment(environment_file, fastmode=(True if mode == MODE_FAST else False))
    environment.place_camera([0, 0, 10.0])
    environment.aim_camera([0.7, 0, 3.3])
```

morse crashes with the following exception:

```
Python script error - object 'Head_Empty.001', controller 'Head_Position':
Traceback (most recent call last):
  File "/opt/sara_morse/lib/python3.3/site-packages/morse/blender/human_interaction/head.py", line 13, in set_body_position
    human = blenderapi.scene().objects[ow.parent["human_name"]]
KeyError: 'value = gameOb[key]: KX_GameObject, key "human_name" does not exist'
Python script error - object 'Human_Camera.001', controller 'camera':
Traceback (most recent call last):
  File "/opt/sara_morse/lib/python3.3/site-packages/morse/blender/human_interaction/camera.py", line 119, in change
    human = sobList[ow["human_name"]]
KeyError: 'value = gameOb[key]: KX_GameObject, key "human_name" does not exist'
```

Moreover, the hierarchy of the objects in Blender seems wrong:
![image](https://cloud.githubusercontent.com/assets/331795/3976597/12cb9c14-2827-11e4-9f69-9ad9ee1d48a6.png)

**Comment by maccradar** [comment]
Has this been patched yet?

**Comment by adegroote** [comment]
I don't think. It needs a complete rewrite on the human model. @severin-lemaignan  has started some work on it, but I don't think he get time to finish it.

**Comment by severin-lemaignan** [comment]
So, I've landed a 'cleaned-up' human avatar (#682), but it does not solve this issue, which is actually unrelated to the human avatar itself. It is really a renaming issue that could possibly impact other robots.

**Comment by severin-lemaignan** [comment]
Well, actually, using AbstractComponent.get_child (as suggested by @adegroote) neatly fixes the issue.

**Comment by maccradar** [comment]
How can I patch this concretely? Where should AbstractComponent.get_child be used or is it included in your human_next branch, which I am currently on?

Creating 2 humans using a name now causes a mix up of the children:

```sh
[    0.259] Robots in the simulation:
[    0.259] 	ROBOT: 'James'
[    0.259] 		- Component: 'James.odometry'
[    0.259] 		- Component: 'James.pose'
[    0.259] 		- Component: 'James.motion'
[    0.259] 		- Component: 'James.skeleton'
[    0.259] 		- Component: 'James.skeleton.joint_states'
[    0.259] 		- Component: 'Raul.skeleton.joint_states'
[    0.259] 	ROBOT: 'Raul'
[    0.259] 		- Component: 'Raul.odometry'
[    0.259] 		- Component: 'Raul.pose'
[    0.259] 		- Component: 'Raul.motion'
```

And causes pymorse to complain:

```sh
Traceback (most recent call last):
  File "replay_human_client.py", line 563, in <module>
    replay.run()
  File "replay_human_client.py", line 500, in run
    with Morse() as simu:
  File "/usr/local/lib/python3/dist-packages/pymorse/pymorse.py", line 483, in __init__
    self.initialize_api()
  File "/usr/local/lib/python3/dist-packages/pymorse/pymorse.py", line 508, in initialize_api
    self._add_component(robot, component, components[component])
  File "/usr/local/lib/python3/dist-packages/pymorse/pymorse.py", line 561, in _add_component
    (name[-1], subcmpt.name, name[-1]))
RuntimeError: Sub-component name <joint_states> conflicts with<skeleton.joint_states> member. To use pymorse with this scenario,please change the name of the sub-component.
```

**Comment by severin-lemaignan** [comment]
@adegroote The 'multiple humans' unit-test [has been updated to check for effective access to the joint state](https://github.com/severin-lemaignan/morse/blob/fa8292c56128f3b583dc6b9bd6aff8e47a07ac0e/testing/human/multiple_human.py#L56). For that to neatly work, I had to change the way `add_default_interface` work (it now applies recursively): 221480a1bd8dc
