### ISSUE TITLE
AttributeError: 'AlwaysSensor' object has no attribute 'frequency'

### ISSUE THREAD

**Issue by pringlized** [morse-simulator/morse#638]
I'm new to Morse.  Great project!  I really appreciate all the work that has been put into it. 

Installed it recently using the [Homebrew instructions](http://www.openrobots.org/morse/doc/1.3/user/installation/package_manager/homebrew_osx.html) on my MacBookPro running Yosemite 10.10.3.  Running the initial sockets tutorial and also connecting to it from a socket client works fine. I added a few things like a light, and had it just drive in a circle.  No problem.  But when I start adding a variety of sensors it errors out with: AttributeError: 'AlwaysSensor' object has no attribute 'frequency'

I tested a variety of sensors and most fail on creating the object: SemanticCamera, VideoCamera, SickLRDS, Proximity, etc..  But some do work like: Pose, Collision, etc..

Been digging through source code even though not very familiar with Blender's source or Morse.  Haven't been able to nail down the culprit yet.  Any help would be much appreciated. Thanks.

##### Running tutorial code with a Proximity sensor
```
$ morse run tutorial-1-sockets.py 
* Loading simulation </Users/jim/Dev/morse-sim/tutorials/tutorial-1-sockets.py>.

* morse 1.3-dirty

* MORSE has only been tested on Linux. It may work
on other operating systems as well, but without any guarantee

* Version 2.75.0 of Blender is untested but should work

ndof: 3Dx driver not found
found bundled python: /Applications/Blender_2.75/blender.app/Contents/MacOS/../Resources/2.75/python
read blend: /usr/local/share/morse/data/morse_default_autorun.blend
[ERROR][MORSE] Uncaught exception, quit Blender.
Traceback (most recent call last):
  File "/Users/user/Dev/morse-sim/tutorials/tutorial-1-sockets.py", line 17, in <module>
    proximity = Proximity()
  File "/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/builder/sensors.py", line 111, in __init__
    self.frequency(12)
  File "/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/builder/abstractcomponent.py", line 523, in frequency
    morselogic[0].frequency = delay
AttributeError: 'AlwaysSensor' object has no attribute 'frequency'
Traceback (most recent call last):
  File "/Users/user/Dev/morse-sim/tutorials/tutorial-1-sockets.py", line 17, in <module>
    proximity = Proximity()
  File "/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/builder/sensors.py", line 111, in __init__
    self.frequency(12)
  File "/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/builder/abstractcomponent.py", line 523, in frequency
    morselogic[0].frequency = delay
AttributeError: 'AlwaysSensor' object has no attribute 'frequency'
```

##### Running tutorial WITHOUT Proximity sensor
```
$ morse run tutorial-1-sockets.py 
* Loading simulation </Users/user/Dev/morse-sim/tutorials/tutorial-1-sockets.py>.

* morse 1.3-dirty

* MORSE has only been tested on Linux. It may work
on other operating systems as well, but without any guarantee

* Version 2.75.0 of Blender is untested but should work

ndof: 3Dx driver not found
found bundled python: /Applications/Blender_2.75/blender.app/Contents/MacOS/../Resources/2.75/python
read blend: /usr/local/share/morse/data/morse_default_autorun.blend
morse.sensors.collision.Collision: no interfaces available for this component! Trying to use default one for socket.
Detected GL_ARB_texture_env_combine
Detected GL_ARB_texture_cube_map
Detected GL_ARB_multitexture
Detected GL_ARB_shader_objects
Detected GL_ARB_vertex_shader
Detected GL_ARB_fragment_shader
Detected GL_ARB_vertex_program
Detected GL_ARB_depth_texture
Detected GL_EXT_separate_specular_color

Blender Game Engine Started
==============================
Welcome to the MORSE simulator
==============================

[PRE-INITIALIZATION]
[    0.014] Python Version: 3.4.2
[    0.014] Blender Version: 2.75.0
[    0.014] Python path: ['/usr/local/share/morse/data', '/usr/local/share/morse/data/props', '/usr/local/share/morse/data/environments/indoors-1', '/usr/local/share/morse/data/actuators', '/usr/local/share/morse/data/robots', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/scripts/addons', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/scripts/modules', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/scripts/startup', '/Applications/Blender_2.75/blender.app/Contents/MacOS/../Resources/2.75/scripts/modules', '/usr/local/Cellar/morse-simulator/1.3/bin', '/Library/Frameworks/Python.framework/Versions/3.4/bin/python3', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python34.zip', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/plat-darwin', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages', '/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/python/lib/python34.zip', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/python/lib/python3.4', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/python/lib/python3.4/plat-darwin', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/python/lib/python3.4/lib-dynload', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/python/lib/python3.4/site-packages', '/Applications/Blender_2.75/blender.app/Contents/MacOS/../Resources/2.75/scripts/freestyle/modules', '/Applications/Blender_2.75/blender.app/Contents/Resources/2.75/scripts/addons/modules', '/Users/jim/Library/Application Support/Blender/2.75/scripts/addons/modules', '/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/blender', '/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/blender/human_interaction']
[    0.014] PID: 25179
[    0.014] [core.morse_time] Morse configured in Best Effort Mode
[    0.015] Added RedBox as a active object
[    0.015] Added GreenBox as a active object
[    0.015] Added BlueBox as a active object
[    0.075] [robots.atrv] atrv initialization
Method SCA_ISensor.frequency is deprecated, please use SCA_ISensor.skippedTicks instead.
/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/core/object.py:56
[    0.075] [robots.atrv] Component initialized
[    0.112] [actuators.v_omega] atrv.motion initialization
[    0.112] [actuators.v_omega] Component initialized
[    0.112] Component atrv.motion  added to atrv
[    0.189] [sensors.pose] atrv.pose initialization
[    0.190] [sensors.pose] Component initialized, runs at 60.00 Hz
[    0.191] Component atrv.pose  added to atrv
[    0.274] [actuators.light] atrv.light initialization
[    0.275] [actuators.light] Component initialized
[    0.276] Component atrv.light  added to atrv
[    0.277] [sensors.collision] atrv.collision initialization
[    0.278] [core.object] Can't get frequency for atrv.collision as the Game Logic sensor calling the action can't be found.
[    0.278] [sensors.collision] Component initialized, runs at 60.00 Hz
[    0.279] Component atrv.collision  added to atrv
[    0.319] [sensors.battery] atrv.battery initialization
[    0.320] [sensors.battery] Component initialized, runs at 60.00 Hz
[    0.320] Component atrv.battery  added to atrv
[    0.369] [actuators.gripper] atrv.gripper initialization
[    0.370] [actuators.gripper] Component initialized
[    0.370] Component atrv.gripper  added to atrv

[SUPERVISION SERVICES INITIALIZATION]
[    0.377] No multi-node scene configuration file found. Multi-node support disabled.
[    0.452] [middleware.socket_request_manager] Socket service manager now listening on port 4000.
[    0.452] [core.services] Successfully initialized the morse.middleware.socket_request_manager.SocketRequestManager request manager.
[    0.452] Adding 'morse.middleware.socket_request_manager.SocketRequestManager' to the middlewares for simulation control
[    0.453] [core.request_manager] Socket service manager: Synchronous service 'activate' for component 'simulation' successfully registered
[    0.453] [core.request_manager] Socket service manager: Synchronous service 'deactivate' for component 'simulation' successfully registered
[    0.453] [core.request_manager] Socket service manager: Synchronous service 'details' for component 'simulation' successfully registered
[    0.453] [core.request_manager] Socket service manager: Synchronous service 'get_camarafp_projection_matrix' for component 'simulation' successfully registered
[    0.453] [core.request_manager] Socket service manager: Synchronous service 'get_scene_objects' for component 'simulation' successfully registered
[    0.454] [core.request_manager] Socket service manager: Synchronous service 'list_robots' for component 'simulation' successfully registered
[    0.454] [core.request_manager] Socket service manager: Synchronous service 'quit' for component 'simulation' successfully registered
[    0.454] [core.request_manager] Socket service manager: Synchronous service 'reset_objects' for component 'simulation' successfully registered
[    0.454] [core.request_manager] Socket service manager: Synchronous service 'restore_dynamics' for component 'simulation' successfully registered
[    0.454] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_far_clip' for component 'simulation' successfully registered
[    0.454] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_position' for component 'simulation' successfully registered
[    0.454] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_projection_matrix' for component 'simulation' successfully registered
[    0.455] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_transform' for component 'simulation' successfully registered
[    0.455] [core.request_manager] Socket service manager: Synchronous service 'set_log_level' for component 'simulation' successfully registered
[    0.455] [core.request_manager] Socket service manager: Synchronous service 'set_object_dynamics' for component 'simulation' successfully registered
[    0.455] [core.request_manager] Socket service manager: Synchronous service 'set_object_visibility' for component 'simulation' successfully registered
[    0.455] [core.request_manager] Socket service manager: Synchronous service 'suspend_dynamics' for component 'simulation' successfully registered
[    0.455] [core.request_manager] Socket service manager: Synchronous service 'terminate' for component 'simulation' successfully registered
[    0.455] Adding 'morse.middleware.socket_request_manager.SocketRequestManager' to the middlewares for time control
[    0.456] [core.request_manager] Socket service manager: Synchronous service 'mode' for component 'time' successfully registered
[    0.456] [core.request_manager] Socket service manager: Synchronous service 'now' for component 'time' successfully registered
[    0.456] [core.request_manager] Socket service manager: Asynchronous service 'sleep' for component 'time' successfully registered
[    0.456] [core.request_manager] Socket service manager: Synchronous service 'statistics' for component 'time' successfully registered
[    0.456] Adding 'morse.middleware.socket_request_manager.SocketRequestManager' to the middlewares for communication control
[    0.457] [core.request_manager] Socket service manager: Synchronous service 'distance_and_view' for component 'communication' successfully registered
[SUPERVISION SERVICES INITIALIZED]

[SCENE INITIALIZATION]
[    0.458] [core.request_manager] Socket service manager: Synchronous service 'get_configurations' for component 'atrv.collision' successfully registered
[    0.458] [core.request_manager] Socket service manager: Synchronous service 'get_local_data' for component 'atrv.collision' successfully registered
[    0.458] [core.request_manager] Socket service manager: Synchronous service 'get_properties' for component 'atrv.collision' successfully registered
[    0.460] [core.request_manager] Socket service manager: Synchronous service 'set_property' for component 'atrv.collision' successfully registered
[    0.461] Component: 'atrv.collision' using middleware 'morse.middleware.socket_request_manager.SocketRequestManager' for services
[    0.461] [core.request_manager] Socket service manager: Synchronous service 'get_configurations' for component 'atrv.light' successfully registered
[    0.461] [core.request_manager] Socket service manager: Synchronous service 'get_properties' for component 'atrv.light' successfully registered
[    0.461] [core.request_manager] Socket service manager: Synchronous service 'set_property' for component 'atrv.light' successfully registered
[    0.462] [core.request_manager] Socket service manager: Synchronous service 'toggle' for component 'atrv.light' successfully registered
[    0.462] Component: 'atrv.light' using middleware 'morse.middleware.socket_request_manager.SocketRequestManager' for services
[    0.462] [core.request_manager] Socket service manager: Synchronous service 'get_configurations' for component 'atrv.pose' successfully registered
[    0.462] [core.request_manager] Socket service manager: Synchronous service 'get_local_data' for component 'atrv.pose' successfully registered
[    0.462] [core.request_manager] Socket service manager: Synchronous service 'get_properties' for component 'atrv.pose' successfully registered
[    0.462] [core.request_manager] Socket service manager: Synchronous service 'set_property' for component 'atrv.pose' successfully registered
[    0.463] Component: 'atrv.pose' using middleware 'morse.middleware.socket_request_manager.SocketRequestManager' for services
[    0.463] [core.request_manager] Socket service manager: Synchronous service 'get_configurations' for component 'atrv.motion' successfully registered
[    0.463] [core.request_manager] Socket service manager: Synchronous service 'get_properties' for component 'atrv.motion' successfully registered
[    0.463] [core.request_manager] Socket service manager: Synchronous service 'set_property' for component 'atrv.motion' successfully registered
[    0.463] [core.request_manager] Socket service manager: Synchronous service 'set_speed' for component 'atrv.motion' successfully registered
[    0.464] [core.request_manager] Socket service manager: Synchronous service 'stop' for component 'atrv.motion' successfully registered
[    0.464] Component: 'atrv.motion' using middleware 'morse.middleware.socket_request_manager.SocketRequestManager' for services
[    0.464] Component: 'atrv.collision' using datastream 'morse.middleware.socket_datastream.SocketDatastreamManager'
[    0.464] [core.request_manager] Socket service manager: Synchronous service 'list_streams' for component 'simulation' successfully registered
[    0.464] [core.request_manager] Socket service manager: Synchronous service 'get_stream_port' for component 'simulation' successfully registered
[    0.464] [core.request_manager] Socket service manager: Synchronous service 'get_all_stream_ports' for component 'simulation' successfully registered
[    0.464] 	Datastream interface 'morse.middleware.socket_datastream.SocketDatastreamManager' created
[    0.465] [middleware.socket_datastream] Socket Mw Server now listening on port 60000 for component atrv.collision.
[    0.465] Component: 'atrv.light' using datastream 'morse.middleware.socket_datastream.SocketDatastreamManager'
[    0.465] [middleware.socket_datastream] Socket Mw Server now listening on port 60001 for component atrv.light.
[    0.465] Component: 'atrv.pose' using datastream 'morse.middleware.socket_datastream.SocketDatastreamManager'
[    0.465] [middleware.socket_datastream] Socket Mw Server now listening on port 60002 for component atrv.pose.
[    0.466] Component: 'atrv.motion' using datastream 'morse.middleware.socket_datastream.SocketDatastreamManager'
[    0.466] [middleware.socket_datastream] Socket Mw Server now listening on port 60003 for component atrv.motion.
[    0.466] 
[    0.466] ------------------------------------
[    0.466] -        SIMULATION SUMMARY        -
[    0.466] ------------------------------------
[    0.466] Robots in the simulation:
[    0.467] 	ROBOT: 'atrv'
[    0.467] 		- Component: 'atrv.motion'
[    0.467] 		- Component: 'atrv.pose'
[    0.467] 		- Component: 'atrv.light'
[    0.467] 		- Component: 'atrv.collision'
[    0.467] 		- Component: 'atrv.battery'
[    0.467] 		- Component: 'atrv.gripper'
[    0.467] Available services:
[    0.467] 	- Interface morse.middleware.socket_request_manager.SocketRequestManager
[    0.467] 		- atrv.motion: ['set_property', 'set_speed', 'get_properties', 'stop', 'get_configurations']
[    0.467] 		- simulation: ['set_camarafp_far_clip', 'list_streams', 'set_object_dynamics', 'deactivate', 'get_all_stream_ports', 'list_robots', 'details', 'reset_objects', 'get_scene_objects', 'set_log_level', 'set_object_visibility', 'set_camarafp_transform', 'set_camarafp_position', 'suspend_dynamics', 'quit', 'get_camarafp_projection_matrix', 'terminate', 'activate', 'get_stream_port', 'set_camarafp_projection_matrix', 'restore_dynamics']
[    0.467] 		- atrv.pose: ['get_configurations', 'get_local_data', 'get_properties', 'set_property']
[    0.467] 		- atrv.light: ['set_property', 'toggle', 'get_configurations', 'get_properties']
[    0.468] 		- atrv.collision: ['get_properties', 'set_property', 'get_configurations', 'get_local_data']
[    0.468] 		- time: ['sleep', 'now', 'statistics', 'mode']
[    0.468] 		- communication: ['distance_and_view']
[    0.468] Modifiers in use:
[    0.468] 	None
[    0.468] 
[    0.468] Datastream interfaces configured:
[    0.468] 	- 'morse.middleware.socket_datastream.SocketDatastreamManager'
[    0.468] ------------------------------------
[    0.468] 
[SCENE INITIALIZED]
```

---

##### Installing morse
```
$ brew tap morse-simulator/morse
$ brew install morse-simulator --with-ros --with-pymorse
```

##### Checking morse environment
```
$ morse check
* Checking up your environment...
* MORSE has only been tested on Linux. It may work
on other operating systems as well, but without any guarantee
* Found MORSE libraries in '/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/blender'. Alright.
* Trying to figure out a prefix from the script location...
* Default scene found. The prefix seems ok. Using it.
* Setting $MORSE_ROOT environment variable to default prefix [/usr/local/]
* Checking version of /Applications/Blender_2.75/blender.app/Contents/MacOS/blender... Found v.2.75.0
* Version 2.75.0 of Blender is untested but should work
* Blender found from $MORSE_BLENDER. Using it (Blender v.2.75.0)
* Checking version of Python within Blender /Applications/Blender_2.75/blender.app/Contents/MacOS/blender... Found v.3.4.2
* Blender and Morse are using Python 3.4.2. Alright.
* Your environment is correctly setup to run MORSE.
```

##### Tutorial code with Proximity sensor
```python
from morse.builder import *

# Land robot
atrv = ATRV()

# Proximity sensor
# AttributeError: 'AlwaysSensor' object has no attribute 'frequency'
proximity = Proximity()

# create a gripper
gripper = Gripper()
gripper.translate(z=.75, x=.3, y=0)
atrv.append(gripper)

# create a battery sensor
battery = Battery()
battery.translate(z=.75, x=-.2, y=0)
atrv.append(battery)

# creates a new collision sensor
collision = Collision()
collision.translate(z = .75, x = .2, y = 0)
atrv.append(collision)

# Light actuator sensor
light = Light()
light.translate(z = 1)
atrv.append(light)

# add a sensor
pose = Pose()
pose.translate(z = 0.75)
atrv.append(pose)

# add an acuator
motion = MotionVW()
atrv.append(motion)

# Scene configuration
collision.add_interface('socket')
light.add_interface('socket')
motion.add_service('socket')
motion.add_stream('socket')
pose.add_service('socket')
pose.add_stream('socket')

# Environment configuration
env = Environment('indoors-1/boxes')
env.set_camera_location([5, -5, 6])
env.set_camera_rotation([1.0470, 0, 0.7854])
```

##### Client code
```python
from pymorse import Morse

def pose_received(pose):
    print("The Robot is currently at %s" % pose)

def main():

    with Morse() as morse:
        morse.atrv.pose.subscribe(pose_received)
        motion = morse.atrv.motion

        v = 1.5
        w = 1

        while True:
            motion.publish({"v": v, "w": w})

if __name__ == "__main__":
    main()
```

**Comment by pringlized** [comment]
Can't believe I missed this in the PRE-INITIALIZATION:

```
Method SCA_ISensor.frequency is deprecated, please use SCA_ISensor.skippedTicks instead.
/usr/local/Cellar/morse-simulator/1.3/lib/python3.4/site-packages/morse/core/object.py:56
```

I'm guessing that maybe my version of Blender isn't using SCA_ISensor.frequency any longer?

**Comment by adegroote** [comment]
Yes, it is a change in blender API in 2.75. This is handled by a0364ae2ec3f819282b1d5037d7ec01483fcc83f in master and 54f1b72c0ab4291653daf394c0b5267dc5aead58 in 1.3_STABLE. But the release 1.3 does not have the patch

**Comment by pringlized** [comment]
Thank you. Feel free to close the issue.
